### ISSUE TITLE
Cannot load a pickle file containing an array

### ISSUE THREAD

**Issue by aabadie** [dask/hdfs3#108]
Tested with python 3.5

Here is a small snippet reproducing the problem:
```python
import pickle
import array
from hdfs3 import HDFileSystem

hdfs = HDFileSystem(host='localhost', port=8020)

a = array.array('d', [1, 2, 3, 4])

# Dump works and the pickle is valid:
# (when retrieved locally using hadoop CLI, pickle can load it)
with hdfs.open("/user/aabadie/test.pkl", "wb") as f:
    pickle.dump(a, f)

# But loading via hdfs file object fails:
with hdfs.open("/user/aabadie/test.pkl", "rb") as f:
    print(pickle.load(f))
```
Here is the error:
```
---------------------------------------------------------------------------
EOFError                                  Traceback (most recent call last)
<ipython-input-17-d986117cc344> in <module>()
      1 with hdfs.open("/user/aabadie/test.pkl", "rb") as f:
----> 2     print(pickle.load(f))
      3 
      4 
      5 

EOFError: Ran out of input
```

I get the same result if I try to pickle a numpy array insteand of a Python array.

**Comment by martindurant** [comment]
I am looking into it. `pickle.loads(f.read())` appears to work.

**Comment by martindurant** [comment]
OK, here is the solution.
If using text-protocol pickling (which is default if `protocol=None` in `dump), then you must load in text mode, which means:
```
with io.TextIOWrapper(hd.open("/user/aabadie/test.pkl", 'rb')) as f:
    print(pickle.load(f))
```

but you probably want to use one of the more space-efficient binary protocol on writing, e.g., `pickle.dump(a, f, -1)`, in which case loading will work as given. This should also fix #107 .

**Comment by aabadie** [comment]
Hi,

Thanks for you answer !
I could make it partially with what you propose : 
* with Python 3.5, I couln't make it work in any case with `io.TextIOWrapper`, even if I use `dump(a, f, protocol=None)`. Otherwise, it only works without io.TextIOWrapper and with `protocol=pickle.HIGHEST_PROTOCOL` in dump.
* with Python 2.7, I have to use `io.TextIOWrapper` and `protocol=None`. It's also noticeably slower than in python 3.

**Comment by martindurant** [comment]
In python 3, the default protocol is 3, which is binary - you would need to specify protocol=0 to get the text behaviour. In python 2, protocol=0 is the default, and this is known to be very slow. Also note that the higher protocols available with python 3 (3 and 4) are not backwards compatible with python 2.

**Comment by mrocklin** [comment]
protocol=2 is a good safe choice or protocol=pickle.HIGHEST_PROTOCOL

**Comment by aabadie** [comment]
Using `pickle.HIGHEST_PROTOCOL` is the only way to make it work with python 3 (I'm currently using 3.5). With python 2.7, it fails in any case if I use a protocol > 0 (and <=2 ). With protocol = 0, I have to use the io.TextIOWrapper trick. I tested with the following snippet:
```python
import pickle
from hdfs3 import HDFileSystem
import numpy as np

hdfs = HDFileSystem(host='localhost', port=8020)

a = np.arange(10000000)

# prints 2 with python 2.7 and 4 with python 3.5
print(pickle.HIGHEST_PROTOCOL)

with hdfs.open("/test.pkl", "wb") as f:
    pickle.dump(a, f, protocol=pickle.HIGHEST_PROTOCOL)

with hdfs.open("/test.pkl", "rb") as f:
    print(pickle.load(f))
```

I agree that protocol=2 is a good safe choice for python 2 but I cannot make it work. It returns the following error:
```
2
Traceback (most recent call last):
  File "test_hdfs3.py", line 16, in <module>
    print(pickle.load(f))
  File "/home/aabadie/conda3/envs/py27/lib/python2.7/pickle.py", line 1384, in load
    return Unpickler(file).load()
  File "/home/aabadie/conda3/envs/py27/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
KeyError: '\x00'
```

**Comment by martindurant** [comment]
I am puzzled, since `pickle.load` works for a local file but fails for the hdfs one, even though `read()` on those files produces identical output. This is not the only case in which this has been seen: http://stackoverflow.com/questions/6331901/pickling-error-in-python , so apparently pickle is assuming something unusual about the file. In any case, doing `read()` and then `pickle.loads` works in every case.

Unless you have any further ideas, @aabadie , I intend to close this.

**Comment by aabadie** [comment]
Thanks for having a look.

Maybe there's something about the encoding (unicode/ascii) conversion between string and bytes. I'm really an expert regarding those thing.

In the end, my use case is to be able to dump/load numpy arrays using [joblib](http://github.com/joblib/joblib) persistence functions.

You can close this. I'll have a look later and will see if I can come up with a solution (and a PR ;) ).

**Comment by ikrambennasrbennasr** [comment]
Hello , please i run this code :

exp_number = 13
model.summary()
from numpy.core import multiarray
import cPickle as pickle
losses = pickle.load( open('/home/ubuntu/nilmtk/nilmtk/neuralnilm/tmpdata/history_exp' + str(exp_number) + '.pickle' , 'rb'))
test_set = pickle.load( open('/home/ubuntu/nilmtk/nilmtk/neuralnilm/tmpdata/TestSet.pickle', 'rb'))
X_test = test_set['X_test']
Y_test = test_set["Y_test"]

and i get this issue :

ImportError Traceback (most recent call last)
in ()
5 exp_number = 15
6 with open('/home/ubuntu/nilmtk/nilmtk/neuralnilm/tmpdata/history_exp' + str(exp_number) + '.pickle' , 'rb') as f:
----> 7 losses = pickle.load(f)
8 # load the test set
9 with open('/home/ubuntu/nilmtk/nilmtk/neuralnilm/tmpdata/TestSet.pickle', 'rb') as v:

ImportError: No module named multiarray

can someone please help me

**Comment by martindurant** [comment]
Does this have something to do with `hdfs3`?

I would guess maybe your pickle was written with a much older version of numpy? Pickle is not meant as a long-term storage format.

**Comment by martindurant** [comment]
Well maybe you should submit this to StackOverflow, since it doesn't appear to have anything to do with `hdfs3`. Furthermore, you'd be well advised to specify *how* you created the files you want to load, as people will not be able to verify your problem otherwise.
