### ISSUE TITLE
More usefule conf_to_dict or avoid meaningless conversions

### ISSUE THREAD

**Issue by FlorianWilhelm** [dask/hdfs3#109]
Right now in the function `hdfs3.core.conf_to_dict` there are a lot of conversions going on from string to int, float, bool. Later when the returned dictionary is used as `pars` keyword parameter to the `HDFSFileSystem` constructor the function `ensure_bytes` is used all over to convert int, float, bool and whatever back to string oder bytes which is not working for Python 3 for instance. Python 3 has for instance `to_bytes()` instead of `tobytes()` and many other things changed. 
The actual question is why this conversion is done in the first place??? Couldn't you just remove the conversion in `conf_to_dict` and therefore save the back conversions again in `HDFSFileSystem.connect`???
Okay, that would mean that if you create the dictionary passed to `pars` yourself you have to write `'true'` instead of `True` but it saves you later a lot of headaches when figuring out what the right byte conversion of `True` is.

**Comment by martindurant** [comment]
Can you produce a specific exception related to `tobytes()`? If that has bitten you, it should be fixed quickly.

Would you mind sketching out a PR of how your proposed changes would look? At the moment only the host and port are set automatically from the XML configuration file.
We do want to ensure that appropriate values can also be passed as python parameters, and I am not certain that the syntax required by the hdfsBuilder is identical to the XML syntax in the conf file.

**Comment by FlorianWilhelm** [comment]
When I use `hdfs3.core.hdfs_conf` which more or less calls `hdfs3.core.conf_to_dict` with the right file names then I get a dictionary of parameters which I then pass to the `par` keyword of the `HDFSFileSystem` constructor. This constructor calls then again the `connect` methods and within that the madness begins:
```python
for par, val in self.pars.items():
    if not  _lib.hdfsBuilderConfSetStr(o, ensure_bytes(par), ensure_bytes(val)) == 0:
          warnings.warn('Setting conf parameter %s failed' % par)
```
If you read the docs of the actual libhdfs3 C/C++ library this is perfectly fine and `hdfsBuilderConfSetStr` expects bytes or old-school strings. But since all values of the dictionary we got from `hdfs3.core.conf_to_dict` were converted the function `ensure_bytes` is called which fails in Python 3, just a few examples:
```python
In [6]: from hdfs3.core import ensure_bytes

In [7]: type(ensure_bytes(1.0))
Out[7]: float

In [8]: type(ensure_bytes(True))
Out[8]: bool

In [9]: type(ensure_bytes(1))
Out[9]: int
```
You see that the function `ensure_bytes` actually returned the same type as the input value. If you pass this then to `_lib.hdfsBuilderConfSetStr` the C backend complains about wrong types. 
My point is that fixing `ensure_bytes` is silver but actually thinking about why you convert all types in `hdfs_conf` is gold ;-). 
I could easily create a PR for the gold option. Thing is I just want to know beforehand if this has chances to be accepted since I know that some would argue that actually `ensure_bytes` is the culprit.

**Comment by FlorianWilhelm** [comment]
@martindurant wow that was fast, thanks a bunch :-) Do you think there will be a release soon of the current master branch so that HA is easily available for everyone?

**Comment by martindurant** [comment]
"a release soon" - watch this space
