### ISSUE TITLE
Release version 1.3 on conda

### ISSUE THREAD

**Issue by FlorianWilhelm** [dask/hdfs3#115]
Using pip installs version 1.3 of hdfs3 but conda still install 1.2. Could you also push version 1.3 to the conda repos? Thanks.

**Comment by martindurant** [comment]
Version 0.1.3 is already on the conda forge channel:
`conda install -c conda-forge hdfs3`

**Comment by FlorianWilhelm** [comment]
Oh thx, haven't seen that. Sorry for the noise.
