### ISSUE TITLE
Add HA detection during configuration reading

### ISSUE THREAD

**Issue by sagagliardo** [dask/hdfs3#119]
While https://github.com/dask/hdfs3/pull/118 works around getting the defaults to set correctly so the wrapper will run successfully, the larger issue is that None values need to be valid for HA setups long term. While the configuration can be explicitly stated, detection of HA for Hadoop should be added at some point from configuration.

Will put some time into this in the near future to build this out.

**Comment by martindurant** [comment]
I agree that auto-detecting the system preferences was the aim, but there is an argument that set-ups more complex than the simplest (and most common) should require parameters from the user. Where the line is between "simple" and "complex" is of course arbitrary.

**Comment by sagagliardo** [comment]
HA is not uncommon though. Either way, we have an HA setup at work that is motivating the tech debt work on this, to reduce the amount of hacks involved on our end to make use of HDFS3. When I get around to writing up this functionality I'll test it on our development cluster to confirm.
