### ISSUE TITLE
ModuleNotFoundError: No module named 'hdfs3'

### ISSUE THREAD

**Issue by tobinwang** [dask/hdfs3#154]
how can i solve this problem  in conda

**Comment by martindurant** [comment]
`conda install hdfs3` ?

**Comment by theirman** [comment]
(base) bitnami@debian:~$ python test.py
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from hdfs3 import HDFileSystem
ModuleNotFoundError: No module named 'hdfs3'
(base) bitnami@debian:~$ conda install libhdfs3
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/bitnami/anaconda3

  added / updated specs:
    - libhdfs3


The following NEW packages will be INSTALLED:

  libboost           pkgs/main/linux-64::libboost-1.67.0-h46d08c1_4
  libgcrypt          pkgs/main/linux-64::libgcrypt-1.8.4-h7b6447c_0
  libgpg-error       pkgs/main/linux-64::libgpg-error-1.32-hf484d3e_0
  libgsasl           pkgs/main/linux-64::libgsasl-1.8.0-h7b6447c_3
  libhdfs3           pkgs/main/linux-64::libhdfs3-2.3.0-h2fca0e8_1
  libntlm            pkgs/main/linux-64::libntlm-1.5-h7b6447c_0
  libprotobuf        pkgs/main/linux-64::libprotobuf-3.6.0-hdbcaa40_0


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
(base) bitnami@debian:~$ python test.py
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from hdfs3 import HDFileSystem
ModuleNotFoundError: No module named 'hdfs3'

**Comment by theirman** [comment]
`
(base) bitnami@debian:~$ python test.py
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from hdfs3 import HDFileSystem
ModuleNotFoundError: No module named 'hdfs3'
(base) bitnami@debian:~$ conda install libhdfs3
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/bitnami/anaconda3

  added / updated specs:
    - libhdfs3


The following NEW packages will be INSTALLED:

  libboost           pkgs/main/linux-64::libboost-1.67.0-h46d08c1_4
  libgcrypt          pkgs/main/linux-64::libgcrypt-1.8.4-h7b6447c_0
  libgpg-error       pkgs/main/linux-64::libgpg-error-1.32-hf484d3e_0
  libgsasl           pkgs/main/linux-64::libgsasl-1.8.0-h7b6447c_3
  libhdfs3           pkgs/main/linux-64::libhdfs3-2.3.0-h2fca0e8_1
  libntlm            pkgs/main/linux-64::libntlm-1.5-h7b6447c_0
  libprotobuf        pkgs/main/linux-64::libprotobuf-3.6.0-hdbcaa40_0


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
(base) bitnami@debian:~$ python test.py
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from hdfs3 import HDFileSystem
ModuleNotFoundError: No module named 'hdfs3'
`
