### ISSUE TITLE
Is Hdfs3 support hadoop 1.0? 

### ISSUE THREAD

**Issue by kurossssd** [dask/hdfs3#155]
Hello,

I'm getting the following error with hdfs3 0.3.0 , Hadoop 1.x :

>> from hdfs3 import HDFileSystem
>> hdfs = HDFileSystem ( host = "Hadoop 1.x host', port = 8020 )

Error:
>> ConnectionError : Connection Failed: HdfsRpcExection: Faild to invoke RPC call "getFsStats" on server  
>> Caused by: HdfsEndOfStream: Read 4 bytes failed from host : End of stream

core-site.xml:
>>< fs.default.name ><Hadoop 1.x host>

but I can connect with hadoop client and Hadoop 2.x it works well.
e.g )
  hadoop fs -ls  hdfs://Hadoop 1.x host:8020/

Is Hdfs3(libhdfs3) support hadoop 1.0? if it support well, how can I connect my hadoop 1.0 server?

**Comment by martindurant** [comment]
Honestly, this has not come up, so I don't know. It sounds indeed like it may not be supported. Hadoop 2.x has been around for four years...

**Comment by kurossssd** [comment]
Okay. thank you for the quick reply
