### ISSUE TITLE
pickle file not readable on Mac

### ISSUE THREAD

**Issue by adampara** [dask/hdfs3#175]
I have a pickle file created ('wb') on the linux machine. It reads back fine using Python 2.7.13 |Anaconda 2.3.0 (64-bit)| (default, Dec 20 2016, 23:09:15) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2

I copy (via scp) the pickle file to MacOs (High Sierra). The copy seems to be identical (od -c) to the original. An attempt to read it back with
Python 2.7.16 |Anaconda custom (x86_64)| (default, Mar 14 2019, 16:24:02) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
 produces:

Traceback (most recent call last):
  File "read_plot_plots.py", line 29, in <module>
    fig_handle = pl.load(open(plt_file,'rb'))
  File "/Users/para/anaconda/lib/python2.7/pickle.py", line 1384, in load
    return Unpickler(file).load()
  File "/Users/para/anaconda/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/Users/para/anaconda/lib/python2.7/pickle.py", line 1223, in load_build
    setstate(state)
  File "/Users/para/anaconda/lib/python2.7/site-packages/matplotlib/transforms.py", line 1693, in __setstate__
    self.input_dims = state['input_dims']
KeyError: u'input_dims'

Any helpful suggestions will be appreciated 

Adam Para

**Comment by martindurant** [comment]
A couple of notes:

- this project is no longer actively maintained, so I would not recommend it any more. However if it works for you, and solves your problem, then it may be fine. You might be interested in pyarrow's hdfs, and the independent webhdfs drivers, both of which are available through [fsspec](https://filesystem-spec.readthedocs.io/en/latest/api.html#built-in-implementations)

- pickle is very flexible and useful for temporary keeping of python objects. However it is not meant for long-term storage and certainly not between different platforms/installations. To get pickle to work between machines, you need to be very careful about matching versions.

**Comment by adampara** [comment]
Hi,
Thanks a lot.. It is a pity that your project is no longer maintained. Sounds like a very sensible one..
I have developed several version of my own pickles and it turned out that my problem was due to incompatible versions of matplotib and had nothing to do with the actual contant of the file..
Best..

Adam

**Comment by martindurant** [comment]
>  It is a pity that your project is no longer maintained.

We found that pyarrow's implementation served for most people's needs, and that building the library to correctly identify and use all the possible security modes in HDFS proved too difficult.
