### ISSUE TITLE
Small block sizes

### ISSUE THREAD

**Issue by mrocklin** [dask/hdfs3#23]
I'm not sure if this is possible, but it'd be great if we could tune the block size of files down to very very small.  This would make certain testing activities much easier.  There is currently a `block_size` kwrag in open/File but any use of it results in an error.  I'm not sure why.

**Comment by martindurant** [comment]
There is a system-wide configuration for how small a block size is allowed, `dfs.namenode.fs-limits.min-block-size`, default 1048576.

**Comment by jettify** [comment]
This feature is very useful, since in case of appends tweaking of block size could increase HDFS cluster performance.
