### ISSUE TITLE
Distributed copy command (distcp)

### ISSUE THREAD

**Issue by koverholt** [dask/hdfs3#37]
It would be handy to have a [distcp](https://hadoop.apache.org/docs/r1.2.1/distcp2.html)-like command to copy files into HDFS in parallel.

**Comment by mrocklin** [comment]
Into HDFS from where exactly?

**Comment by koverholt** [comment]
I use `dictcp` most frequently from S3 to HDFS, but it's also commonly used to copy/backup data between clusters.

**Comment by mrocklin** [comment]
This probably doesn't happen at the `hdfs3` level then.  This probably requires an execution engine like `distributed`.

**Comment by koverholt** [comment]
Agreed, I was considering which repo was the right place to put this.

**Comment by martindurant** [comment]
Distributed downloading from S3 using boto already works, is there an explicit need for a no-op before writing, a distcp?

**Comment by mrocklin** [comment]
I plan to close this after https://github.com/blaze/distributed/pull/75 gets in.
