### ISSUE TITLE
HDFS High Availability

### ISSUE THREAD

**Issue by jasonrhaas** [dask/hdfs3#62]
Does the module support HDFS High Availability?  I have a system that  uses primary and secondary namenodes, and when there is a failover it changes which one is the primary namenode.  Looking at the code, it appears to only support one connection or IP address.

**Comment by danielfrg** [comment]
I believe that as long as you have the secondary namenode configured in the `hdfs-site.xml` then `libhdfs3` will failover to the secondary namenode. @wangzw probably can comment on this.

**Comment by wangzw** [comment]
NAMENODE failover is handled on both server and client sides. For client side. libhdfs3 can switch to another namenode and retry if the current namenode fail to response the RPC call or declare itself as standby. But to make it work, you have to configure libhdfs3 correctly in ```hdfs-client.xml```. 

```hdfs-client.xml``` is used by libhdfs3 on client side. The HA configuration is the same as in ```hdfs-site.xml``` on server side.

**Comment by gglanzani** [comment]
Hi @wangzw, does it mean that I should NOT specify host and port? Even when leaving them empty they default to (see https://github.com/dask/hdfs3/blob/master/hdfs3/core.py#L35)

```python
u = urlparse(conf['fs.defaultFS'])  # pragma: no cover
conf['host'] = u.hostname  # pragma: no cover
conf['port'] = u.port  # pragma: no cover
```
where `conf` is set by parsing `core-site.xml`. In HA scenario's, `fs.defaultFS` is something like

```xml
<property>
  <name>fs.defaultFS</name>
  <value>hdfs://mycluster</value>
</property>
```

so `host = 'mycluster'` and `port = None`. These values are then used like so

```python
o = _lib.hdfsNewBuilder()
_lib.hdfsBuilderSetNameNodePort(o, self.port)
 _lib.hdfsBuilderSetNameNode(o, ensure_bytes(self.host))
```

If I then look at the source for `lib`, I see that the ` _lib.hdfsBuilderSetNameNode` has a doc string containing the following:

```
You may specify a NameNode port in the usual way by

             passing a string of the format hdfs://<hostname>:<port>.
```

In this case `mycluster` (or whatever I'm using for HA) does not seem to be valid to me. 

At this point I think `libhdfs3` reads a `hdfs-client.xml` anyway. But wouldn't it be possible (and possibly better) to pass the two namenodes explicitly in the Python client code?

I'm asking as I'd love to have `hdfs3` to be the HDFS library used by Airflow, but the presence of `hdfs-client.xml` can be difficult to require.

**Comment by jettify** [comment]
@gglanzani you can do the following:
```
host = "mycluster"
conf = {"dfs.nameservices": "mycluster",
              "dfs.ha.namenodes. mycluster": "nn1,nn2",
              "dfs.namenode.rpc-address. mycluster.nn1": "myhost1:port",
               "dfs.namenode.rpc-address. mycluster.nn2": "myhost2:port"}
fs = HDFileSystem(host=host, port=None, pars=conf)
```
To overcome port issue I just subclass `HDFileSystem` and remove line with `_lib.hdfsBuilderSetNameNodePort(o, self.port)`. Not to specify any port (even valid) is very important, because `libhdfs3` see the port and do not use HA mode at all (https://github.com/Pivotal-Data-Attic/pivotalrd-libhdfs3/blob/apache-rpc-9/src/client/FileSystemImpl.cpp#L161-L177)

**Comment by martindurant** [comment]
Thank you, that's very nice - this should be documented and included (feel free to make a PR if I don't get to it soon).
On removing `_lib.hdfsBuilderSetNameNodePort(o, self.port)`, what specific condition can I check for to make sure not to call this when HA is being configured?

**Comment by gglanzani** [comment]
Thanks @jettify, that's really helpful! I agree with @martindurant, this should be documented.

**Comment by jettify** [comment]
You can see my dirty changes that work for my project here (https://github.com/dask/hdfs3/compare/dd84c179f32350b23ab07402012db722b08aa700...jettify:be86947bfee9e1e140657e1b8d41cbfbb37e7afb). 

Also we use`hdfs3` with kerberos, tokens and proper user impersonation, but to have those fixed in `hdfs3` this PRs should be merged first (https://github.com/Pivotal-Data-Attic/pivotalrd-libhdfs3/pull/45 https://github.com/Pivotal-Data-Attic/pivotalrd-libhdfs3/pull/28)

**Comment by mrocklin** [comment]
@jettify it would be very cool if you could contribute those upstream, especially with tests.  My guess is that a lot of people would benefit.

**Comment by martindurant** [comment]
Not a lot of merging has been going on at pivotal, recently....

**Comment by gglanzani** [comment]
@martindurant @mrocklin Can we have https://github.com/jettify/hdfs3 merged in though? I don't think there's a need to wait for tokens and user impersonation from `libhdfs3` (although they are nice additions).

**Comment by jettify** [comment]
I will try to find time to do clean PR tomorrow

**Comment by mrocklin** [comment]
Thank you @jettify !

**Comment by quasiben** [comment]
@jettify do you know if your PRs will resolves this issue: https://github.com/Pivotal-Data-Attic/pivotalrd-libhdfs3/issues/53 ?

**Comment by jettify** [comment]
Sorry I do not know, that are PRs of my teammate, may be he knows more.

**Comment by bdrosen96** [comment]
I suspect that it will not fix that linked issue. To resolve that issue, it would require building debug version of lib and using gdb to trace through the call to see where it goes wrong. I think integrity and privacy likely requires different options for gsasl or something. I suspect something related to GSASL_QOP_AUTH_INT as described here: https://www.gnu.org/software/gsasl/reference/gsasl-gsasl.html

**Comment by bdrosen96** [comment]
Perhaps something like this:

sprintf(str, "%d", GSASL_QOP_AUTH_INT );
gsasl_property_set(session, GSASL_QOP, str);

conditionally in SaslClient::initKerberos. Not sure what needs doing for GSASL_QOPS property though - that may be only for the server to use. Or it might require something like this:

https://github.com/markpizz/gsasl/blob/bd1f4f5d9bcc2bfc4896ed0af4a4cdce7812441f/tests/digest-md5.c#L100-L116
