### ISSUE TITLE
read_block should include terminator

### ISSUE THREAD

**Issue by martindurant** [dask/hdfs3#88]
We chop off the end-of-block delimiter when doing read_block, but should not.

**Comment by mrocklin** [comment]
Why or why not?  I have a vague recollection that this was causing trouble for someone at some point?

**Comment by martindurant** [comment]
It fits with things like readline[s]() to keep it. We changed it in s3fs after discussion, but not here. Seeing this now, because I'm adapting these tests for client.

**Comment by mrocklin** [comment]
Alright.  Makes sense to me, especially if other tools agree and usage dictates.
