### ISSUE TITLE
Test hdfs3 with Kerberos authentication

### ISSUE THREAD

**Issue by koverholt** [dask/hdfs3#9]
Related: https://github.com/bloomberg/chef-bach/pull/364

**Comment by mrocklin** [comment]
Has there been any progress here?  Should we be actively bugging anyone about this?

**Comment by koverholt** [comment]
I configured a Kerberized HDFS cluster and successfully used `hdfs3` via Kerberos authentication. A couple of things to note:

* I compiled libgsasl with GSSAPI support (MIT Kerberos) and pushed the updated conda package to the blaze channel on anaconda.org (see updated conda recipe from 9954e32)
* I needed to use the hdfs-client.xml config file from https://github.com/PivotalRD/libhdfs3/wiki/Configure-Parameters

**Comment by KimiRaikking** [comment]
@koverholt  
hi, do you have compiled libgsasl.so file, i can't compile it which should support gssapi

**Comment by martindurant** [comment]
This issue is very old.
I recommend that, if hdfs3 is not working for you, you should try with pyarrow's hdfs module.

**Comment by KimiRaikking** [comment]
@martindurant 
nice, it's ok with pyarrow
