### ISSUE TITLE
Add documentation for HA mode

### ISSUE THREAD

**Issue by martindurant** [dask/hdfs3#92]
(see #90)

**Comment by FlorianWilhelm** [comment]
Hi @martindurant, the HA mode is actually well explained in the C/C++ library this python library uses internally. You find the HA configuration [here](https://github.com/Pivotal-Data-Attic/pivotalrd-libhdfs3/wiki/Configure-Parameters).

But to cut a long story short, you'll basically want to do:
```python
host = "nameservice1"
conf = {"dfs.nameservices": "nameservice1",
        "dfs.ha.namenodes.nameservice1": "namenode113,namenode188",
        "dfs.namenode.rpc-address.nameservice1.namenode113": "hostname_of_server1:8020",
        "dfs.namenode.rpc-address.nameservice1.namenode188": "hostname_of_server2:8020",
        "dfs.namenode.http-address.nameservice1.namenode188": "hostname_of_server1:50070",
        "dfs.namenode.http-address.nameservice1.namenode188": "hostname_of_server2:50070",
        "hadoop.security.authentication": "kerberos"
}
fs = HDFileSystem(host=host, pars=conf)
```
Note that I don't specify a `port` when creating the `HDFileSystem` object which is mandatory for HA. This will **not** work with the currently released version 0.1.2 of hdfs3 but only with the current master branch.

Besides the direct configuration you can of course also opt to put those in an xml file and point the environment variable `LIBHDFS3_CONF` to it which also explained [here](https://github.com/Pivotal-Data-Attic/pivotalrd-libhdfs3/wiki/Configure-Parameters).
