### ISSUE TITLE
MapR compatibility

### ISSUE THREAD

**Issue by stevenmanton** [dask/hdfs3#93]
I understand that libhdfs3 isn't really relevant to MapR since they have their own C API, but it would nice for this library to support MapR. It seems like the MapR API is different enough from libhdfs3 to make this a quick and simple project. Still, it seems a shame to to start a different project instead of adding MapR support to this one.

Any high level thoughts or insights on this?

**Comment by mrocklin** [comment]
I would tend towards many small libraries with very similar interfaces.  For example the [s3fs](http://s3fs.readthedocs.io/en/latest/) project shares this interface for Amazon's S3.  I suspect that trying to unify all of the projects at a low-level would be challenging.  Most of the work in getting these things right has to do with interacting with the low-level system and with testing, neither of which are shared between libraries.  

If more such libraries start to exist (which appears to be happening) we might consider making an abstract base class to formalize the shared API.

**Comment by quasiben** [comment]
What do you mean by support MapR ?  I think of MapR as a distribution of Hadoop.

**Comment by stevenmanton** [comment]
@mrocklin Perfect, I also like the idea of keeping implementations separate as well. One thing I want to make sure is that whatever we develop will be compatible with dask -- that's one of our main uses cases. It seems like we just need to implement the API for a `FileSystem` and `File`? Maybe it would be nice if there were an interface to subclass...

@quasiben MapR is another distro of Hadoop, but they've totally written the Hadoop implement in C rather than Java, which means the API's are a bit different. In general, MapR tends to behave quite a bit different than Cloudera or Hortonworks.

**Comment by mrocklin** [comment]
For inter-operation with Dask the code to look at is here: https://github.com/dask/dask/tree/master/dask/bytes 

You have to write and register a couple of functions that, given a path, produce a list of dask.delayed objects corresponding to blocks of bytes or, given a bunch of dask.delayed value objects of bytes, write those bytes to disk.  

The HDFS version is here: https://github.com/dask/distributed/blob/master/distributed/hdfs.py (ignore the deprecated read_csv and read_text functions) and it does a bit more work to capture the data-local nature of HDFS, but that's optional if you didn't care too strongly about maximizing performance.

As you suggest, as we invest more into this file-object or filesystem-like interface it might be wise to provide a more direct interface.  Historically it has been the matter of about a day to integrate Dask with a library like hdfs3 or s3fs.  I wouldn't be too worried.  If you can serve byte ranges then things are set up fairly well for libraries like dask.dataframe to take advantage of it.  

Pinging @martindurant, who has done most of this work.

**Comment by stevenmanton** [comment]
Awesome. We'll take a look at that stuff and start developing it soon. Thanks for all your help!

**Comment by mrocklin** [comment]
Feel free to be vocal on this issue.  There are a few things we've been talking about changing to make `dask.bytes` simpler to extend (with ideas like File and FileSystem as you mention) but we haven't yet because a good reason hasn't yet arisen.  Depending on how much time developers have you may end up being that reason.

**Comment by quasiben** [comment]
@stevenmanton does MapR not use the protobuf interfaces in Hadoop 2.X ?

**Comment by martindurant** [comment]
@stevenmanton , just to reaffirm mrocklin's comment: please comment early and often, we are keen to expose multiple storage platforms to python, especially in a manner convenient for dask's parallel processing. I have been meaning to to rationalise the read functionality in dask to make it easier to add backends, but haven't made a start on that yet.

**Comment by stevenmanton** [comment]
Thanks everyone! We'll start development on this ASAP and will communicate early and often.

**Comment by stevenmanton** [comment]
So I've been looking into this and I have a working copy that I branched from master. It sounds like there wasn't much appetite for keeping a single repo that is compatible with both libhdfs3 and mapr. Still, there's so much code overlap that maybe we revisit that option. Otherwise, another attractive option would be to maintain a fork that is mapr-only compatible. As hdfs3 continues to develop, at least we could continue to merge in those changes. I would call that package maprfs, but the source code would be largely the same as hdfs3.

I'm hoping to push this code soon to a public repo for comments, but am working that out with our legal team first.

**Comment by mrocklin** [comment]
If it's very similar then it might make sense to keep them together.  It would depend on how cleanly we could support both.  If you have a branch off of this repository then I recommend issuing a PR if only so that everyone can compare the differences.  This would be after you clear it with your legal team of course.

**Comment by stevenmanton** [comment]
@mrocklin sounds good! By the way, does Continuum have any contributor agreements we would need to sign? I'm not too familiar with open source licenses and don't want to get my company in trouble :-)

**Comment by mrocklin** [comment]
Dask projects don't currently require contributor license agreements.  

That being said, you should check with your employer that they're comfortable with you releasing this code to the public.  You're in no danger of getting your company into trouble.  You're mostly checking that they don't think you're leaking internal code by publishing to an open source project.

**Comment by martindurant** [comment]
"using NFS with a single gateway node" - would you mind elaborating what this means?

**Comment by stevenmanton** [comment]
Hey @kmatt we worked on a MapR-compatible library by making some small modifications to the hdfs3 library. You can find our repo [here](https://github.com/IDAnalytics/py-maprfs/tree/maprfs-compatibility). Our work on it kind of fizzled, but I believe it was mostly working last time we used it. We basically wrap MapR's C++ bindings instead of using the libhdfs bindings found in Cloudera or Hortonworks distros.

**Comment by kmatt** [comment]
@martindurant MapR community edition only supports a single NFS gateway node. 

I'm wondering if the Dask processes on multiple cluster nodes are bottlenecked thought the single NFS gateway node because we are accessing files via an NFS mount and not via the hdfs3 lib.

**Comment by kmatt** [comment]
@stevenmanton Thanks! I will try building with MapR 5.2 

Does it expect a local MapR installation for dependencies? Or is there a way to get it to build on a workstation without a full server install, from a MapR client package?

**Comment by stevenmanton** [comment]
Hey @kmatt I don't believe there's anything to build. I think it's mostly just configuring the python source code to point to your MapR's `MapRPythonClient.a` file. Check out the `lib.py` file to see how we modified it to use MapR instead of `libhdfs.so`. My guess is that the path on your distro will be the same.

I can try to get you more info on Monday.

**Comment by kmatt** [comment]
@stevenmanton I was able to get the current maprfs-compatibility branch to install and run and hdfs.ls by adding `export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.91-0.b14.el7_2.x86_64/jre/lib/amd64/server` for libjvm.so

There may be a better way to specify that path in the shell config?
