### ISSUE TITLE
Can not find the shared library:libhdfs3.so

### ISSUE THREAD

**Issue by SharpLu** [dask/hdfs3#97]
Hello, My environment is Ubuntu 16 Desktop version,  I have experienced this problem, when i install hdfs3 with Dask distributed 
Error Can not find the shared library:libhdfs3.so
When I try to run Dask retrieve data from HDFS. Also noticed a lot of people have this issues.
What I was done?

1. conda install hdfs3 -c conda-forge
    conda install distributed hdfs3 -c conda-forge
![a](https://cloud.githubusercontent.com/assets/8836246/20034528/8a432088-a3c1-11e6-8e94-222c9f8b8f9d.PNG)

2. conda install libprotobuf
![c](https://cloud.githubusercontent.com/assets/8836246/20034538/f723204a-a3c1-11e6-97c6-07482daef29f.PNG)

3. 
![d](https://cloud.githubusercontent.com/assets/8836246/20034540/01dd5500-a3c2-11e6-945c-5a4b1bff3808.PNG)

**Comment by SharpLu** [comment]
Also tried [conda install -c clinicalgraphics libgcrypt11](url)

**Comment by SharpLu** [comment]
The problem has resolved. 

conda install libhdfs3
pip install libhdfs3
if still not working , try to update libhdfs3

**Comment by koverholt** [comment]
Thanks for the report. This should be solved in the latest `libhdfs3` conda package that was built from https://github.com/conda-forge/libhdfs3-feedstock/pull/6 with the latest available versions of `protobuf` and `boost`.

I tested `conda install hdfs3 -c conda-forge` on Ubuntu 14.04/16.04 and CentOS 6/7 and things are working for me.

Please reopen if you continue to have issues.

**Comment by leafjungle** [comment]
The document gives these tips in : https://hdfs3.readthedocs.io/en/latest/install.html
"git clone git@github.com:dask/hdfs3
cd hdfs3
python setup.py install"
And "Can not find the shared library: libhdfs3.so"

And I have to install libhdfs3.so 
And then I have to install conda.   

It seems that is a long story.

**Comment by martindurant** [comment]
You may, if you wish, build libhdfs3 yourself. That is a C++ codebase with a set of dependencies of its own. The best way I now how to do this is to use the conda script... but if you have the mindset, the CMake files and README descriptions might get you there.
